--- #YAML:1.0
name:               MP4-File
version:            0.08
abstract:           Read/Write MP4 files
author:
    - Marcus Holland-Moritz <mhx@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Encode:      1.75
    Test::More:  0.45
no_index:
    directory:
        - t
        - inc
        - support
generated_by:       ExtUtils::MakeMaker version 6.55_01
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
